
print("Mark Zuckerburg is the computer scientist I chose.")
print("He was born on May 14, 1984 and still currently living.")
print("He graduated gradutated from Harvard and he also is known for founding facebook.\n")
text = input("Do you know who Mark Zuckerburg is?")
print("They are pretty cool, aren’t they\n.""")
print("():::::()")
print("  /-/")
print(" /-/")
print("/-/")
print("\\\"")
print("\\\\")
print("\\\\\\")
print("\\\\\\\\\"")
print("\\\\\\\\\\\\\:")
print("\------------\"")
print("(0)===))))\------------------\"")
print("------------------------------[::::)0000>")
print("(0)===))))/------------------/""")
print("/-----------/")
print("/////////////:")
print("/////////")
print("///////")
print("////")
print("///")
print("\-\"")
print(" \-\"")
print("  \-\"")
print("():::::()")
